//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HLNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HPNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HFNAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HTIN" type="{}DGHTINF"/>
 *         &lt;element name="HKSTI" type="{}DGc_dpi"/>
 *         &lt;element name="HSTI" type="{}DGHSTI"/>
 *         &lt;element name="HEMAIL" type="{}DGHEMAIL"/>
 *         &lt;element name="HCOUNTRY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HREG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HRAJ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HCITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HSTREET" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HBUILD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HSHOT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HCORP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HAPT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HPASS" type="{}DGPass" minOccurs="0"/>
 *         &lt;element name="HPASSDATE" type="{}DGDate" minOccurs="0"/>
 *         &lt;element name="HPASSISS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="R01G01" type="{}DGKv"/>
 *         &lt;element name="R01G02" type="{}DGNYear"/>
 *         &lt;element name="R02G01" type="{}DGKv"/>
 *         &lt;element name="R02G02" type="{}DGNYear"/>
 *         &lt;element name="HFILL" type="{}DGDate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DBody", propOrder = {
    "hlname",
    "hpname",
    "hfname",
    "htin",
    "hksti",
    "hsti",
    "hemail",
    "hcountry",
    "hreg",
    "hraj",
    "hcity",
    "hstreet",
    "hbuild",
    "hshot",
    "hcorp",
    "hapt",
    "hpass",
    "hpassdate",
    "hpassiss",
    "r01G01",
    "r01G02",
    "r02G01",
    "r02G02",
    "hfill"
})
public class DBody {

    @XmlElement(name = "HLNAME", required = true)
    protected String hlname;
    @XmlElement(name = "HPNAME", required = true)
    protected String hpname;
    @XmlElementRef(name = "HFNAME", type = JAXBElement.class, required = false)
    protected JAXBElement<String> hfname;
    @XmlElement(name = "HTIN", required = true)
    protected String htin;
    @XmlElement(name = "HKSTI")
    protected int hksti;
    @XmlElement(name = "HSTI", required = true)
    protected String hsti;
    @XmlElement(name = "HEMAIL", required = true)
    protected String hemail;
    @XmlElement(name = "HCOUNTRY", required = true)
    protected String hcountry;
    @XmlElementRef(name = "HREG", type = JAXBElement.class, required = false)
    protected JAXBElement<String> hreg;
    @XmlElementRef(name = "HRAJ", type = JAXBElement.class, required = false)
    protected JAXBElement<String> hraj;
    @XmlElement(name = "HCITY", required = true)
    protected String hcity;
    @XmlElement(name = "HSTREET", required = true)
    protected String hstreet;
    @XmlElement(name = "HBUILD", required = true)
    protected String hbuild;
    @XmlElementRef(name = "HSHOT", type = JAXBElement.class, required = false)
    protected JAXBElement<String> hshot;
    @XmlElementRef(name = "HCORP", type = JAXBElement.class, required = false)
    protected JAXBElement<String> hcorp;
    @XmlElementRef(name = "HAPT", type = JAXBElement.class, required = false)
    protected JAXBElement<String> hapt;
    @XmlElementRef(name = "HPASS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> hpass;
    @XmlElementRef(name = "HPASSDATE", type = JAXBElement.class, required = false)
    protected JAXBElement<String> hpassdate;
    @XmlElementRef(name = "HPASSISS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> hpassiss;
    @XmlElement(name = "R01G01")
    protected int r01G01;
    @XmlElement(name = "R01G02")
    protected int r01G02;
    @XmlElement(name = "R02G01")
    protected int r02G01;
    @XmlElement(name = "R02G02")
    protected int r02G02;
    @XmlElement(name = "HFILL", required = true)
    protected String hfill;

    /**
     * Gets the value of the hlname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHLNAME() {
        return hlname;
    }

    /**
     * Sets the value of the hlname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHLNAME(String value) {
        this.hlname = value;
    }

    /**
     * Gets the value of the hpname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPNAME() {
        return hpname;
    }

    /**
     * Sets the value of the hpname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPNAME(String value) {
        this.hpname = value;
    }

    /**
     * Gets the value of the hfname property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHFNAME() {
        return hfname;
    }

    /**
     * Sets the value of the hfname property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHFNAME(JAXBElement<String> value) {
        this.hfname = value;
    }

    /**
     * Gets the value of the htin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHTIN() {
        return htin;
    }

    /**
     * Sets the value of the htin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHTIN(String value) {
        this.htin = value;
    }

    /**
     * Gets the value of the hksti property.
     * 
     */
    public int getHKSTI() {
        return hksti;
    }

    /**
     * Sets the value of the hksti property.
     * 
     */
    public void setHKSTI(int value) {
        this.hksti = value;
    }

    /**
     * Gets the value of the hsti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSTI() {
        return hsti;
    }

    /**
     * Sets the value of the hsti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSTI(String value) {
        this.hsti = value;
    }

    /**
     * Gets the value of the hemail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHEMAIL() {
        return hemail;
    }

    /**
     * Sets the value of the hemail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHEMAIL(String value) {
        this.hemail = value;
    }

    /**
     * Gets the value of the hcountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHCOUNTRY() {
        return hcountry;
    }

    /**
     * Sets the value of the hcountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHCOUNTRY(String value) {
        this.hcountry = value;
    }

    /**
     * Gets the value of the hreg property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHREG() {
        return hreg;
    }

    /**
     * Sets the value of the hreg property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHREG(JAXBElement<String> value) {
        this.hreg = value;
    }

    /**
     * Gets the value of the hraj property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHRAJ() {
        return hraj;
    }

    /**
     * Sets the value of the hraj property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHRAJ(JAXBElement<String> value) {
        this.hraj = value;
    }

    /**
     * Gets the value of the hcity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHCITY() {
        return hcity;
    }

    /**
     * Sets the value of the hcity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHCITY(String value) {
        this.hcity = value;
    }

    /**
     * Gets the value of the hstreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSTREET() {
        return hstreet;
    }

    /**
     * Sets the value of the hstreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSTREET(String value) {
        this.hstreet = value;
    }

    /**
     * Gets the value of the hbuild property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHBUILD() {
        return hbuild;
    }

    /**
     * Sets the value of the hbuild property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHBUILD(String value) {
        this.hbuild = value;
    }

    /**
     * Gets the value of the hshot property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHSHOT() {
        return hshot;
    }

    /**
     * Sets the value of the hshot property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHSHOT(JAXBElement<String> value) {
        this.hshot = value;
    }

    /**
     * Gets the value of the hcorp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHCORP() {
        return hcorp;
    }

    /**
     * Sets the value of the hcorp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHCORP(JAXBElement<String> value) {
        this.hcorp = value;
    }

    /**
     * Gets the value of the hapt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHAPT() {
        return hapt;
    }

    /**
     * Sets the value of the hapt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHAPT(JAXBElement<String> value) {
        this.hapt = value;
    }

    /**
     * Gets the value of the hpass property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHPASS() {
        return hpass;
    }

    /**
     * Sets the value of the hpass property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHPASS(JAXBElement<String> value) {
        this.hpass = value;
    }

    /**
     * Gets the value of the hpassdate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHPASSDATE() {
        return hpassdate;
    }

    /**
     * Sets the value of the hpassdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHPASSDATE(JAXBElement<String> value) {
        this.hpassdate = value;
    }

    /**
     * Gets the value of the hpassiss property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHPASSISS() {
        return hpassiss;
    }

    /**
     * Sets the value of the hpassiss property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHPASSISS(JAXBElement<String> value) {
        this.hpassiss = value;
    }

    /**
     * Gets the value of the r01G01 property.
     * 
     */
    public int getR01G01() {
        return r01G01;
    }

    /**
     * Sets the value of the r01G01 property.
     * 
     */
    public void setR01G01(int value) {
        this.r01G01 = value;
    }

    /**
     * Gets the value of the r01G02 property.
     * 
     */
    public int getR01G02() {
        return r01G02;
    }

    /**
     * Sets the value of the r01G02 property.
     * 
     */
    public void setR01G02(int value) {
        this.r01G02 = value;
    }

    /**
     * Gets the value of the r02G01 property.
     * 
     */
    public int getR02G01() {
        return r02G01;
    }

    /**
     * Sets the value of the r02G01 property.
     * 
     */
    public void setR02G01(int value) {
        this.r02G01 = value;
    }

    /**
     * Gets the value of the r02G02 property.
     * 
     */
    public int getR02G02() {
        return r02G02;
    }

    /**
     * Sets the value of the r02G02 property.
     * 
     */
    public void setR02G02(int value) {
        this.r02G02 = value;
    }

    /**
     * Gets the value of the hfill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHFILL() {
        return hfill;
    }

    /**
     * Sets the value of the hfill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHFILL(String value) {
        this.hfill = value;
    }

}
