//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeclarContent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeclarContent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DECLARHEAD" type="{}DHead"/>
 *         &lt;element name="DECLARBODY" type="{}DBody"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "DECLAR")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeclarContent", propOrder = {
    "declarhead",
    "declarbody"
})
public class DeclarContent {

    @XmlElement(name = "DECLARHEAD", required = true)
    protected DHead declarhead;
    @XmlElement(name = "DECLARBODY", required = true)
    protected DBody declarbody;

    /**
     * Gets the value of the declarhead property.
     * 
     * @return
     *     possible object is
     *     {@link DHead }
     *     
     */
    public DHead getDECLARHEAD() {
        return declarhead;
    }

    /**
     * Sets the value of the declarhead property.
     * 
     * @param value
     *     allowed object is
     *     {@link DHead }
     *     
     */
    public void setDECLARHEAD(DHead value) {
        this.declarhead = value;
    }

    /**
     * Gets the value of the declarbody property.
     * 
     * @return
     *     possible object is
     *     {@link DBody }
     *     
     */
    public DBody getDECLARBODY() {
        return declarbody;
    }

    /**
     * Sets the value of the declarbody property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBody }
     *     
     */
    public void setDECLARBODY(DBody value) {
        this.declarbody = value;
    }

}
