//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DGJ02095Ind4.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DGJ02095Ind4">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="А1"/>
 *     &lt;enumeration value="А2"/>
 *     &lt;enumeration value="А3"/>
 *     &lt;enumeration value="А4"/>
 *     &lt;enumeration value="А5"/>
 *     &lt;enumeration value="А6"/>
 *     &lt;enumeration value="А7"/>
 *     &lt;enumeration value="А8"/>
 *     &lt;enumeration value="А9"/>
 *     &lt;enumeration value="А10"/>
 *     &lt;enumeration value="А11.1"/>
 *     &lt;enumeration value="А11.2"/>
 *     &lt;enumeration value="А12.1"/>
 *     &lt;enumeration value="А12.2"/>
 *     &lt;enumeration value="А13"/>
 *     &lt;enumeration value="А14"/>
 *     &lt;enumeration value="А15"/>
 *     &lt;enumeration value="Б1"/>
 *     &lt;enumeration value="Б2"/>
 *     &lt;enumeration value="Б3"/>
 *     &lt;enumeration value="Б4"/>
 *     &lt;enumeration value="Б5"/>
 *     &lt;enumeration value="Б6"/>
 *     &lt;enumeration value="Б7"/>
 *     &lt;enumeration value="Б8"/>
 *     &lt;enumeration value="Б9.1"/>
 *     &lt;enumeration value="Б9.2"/>
 *     &lt;enumeration value="Б10"/>
 *     &lt;enumeration value="Б10.1"/>
 *     &lt;enumeration value="Б10.2"/>
 *     &lt;enumeration value="Б11"/>
 *     &lt;enumeration value="Б12"/>
 *     &lt;enumeration value="В1"/>
 *     &lt;enumeration value="В2"/>
 *     &lt;enumeration value="В3"/>
 *     &lt;enumeration value="В4"/>
 *     &lt;enumeration value="В5"/>
 *     &lt;enumeration value="В6"/>
 *     &lt;enumeration value="В7"/>
 *     &lt;enumeration value="В8"/>
 *     &lt;enumeration value="В9"/>
 *     &lt;enumeration value="В10.1"/>
 *     &lt;enumeration value="В10.2"/>
 *     &lt;enumeration value="В12"/>
 *     &lt;enumeration value="В13"/>
 *     &lt;enumeration value="В14"/>
 *     &lt;enumeration value="В15"/>
 *     &lt;enumeration value="Г1"/>
 *     &lt;enumeration value="Г2"/>
 *     &lt;enumeration value="Г3"/>
 *     &lt;enumeration value="Г4"/>
 *     &lt;enumeration value="Г5"/>
 *     &lt;enumeration value="Г6"/>
 *     &lt;enumeration value="Г7"/>
 *     &lt;enumeration value="Г8.1"/>
 *     &lt;enumeration value="Г8.2"/>
 *     &lt;enumeration value="Г9"/>
 *     &lt;enumeration value="Г10"/>
 *     &lt;enumeration value="Ґ1"/>
 *     &lt;enumeration value="Д1.1"/>
 *     &lt;enumeration value="Д1.2"/>
 *     &lt;enumeration value="Д2.1"/>
 *     &lt;enumeration value="Д2.2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DGJ02095Ind4")
@XmlEnum
public enum DGJ02095Ind4 {

    @XmlEnumValue("\u04101")
    А_1("\u04101"),
    @XmlEnumValue("\u04102")
    А_2("\u04102"),
    @XmlEnumValue("\u04103")
    А_3("\u04103"),
    @XmlEnumValue("\u04104")
    А_4("\u04104"),
    @XmlEnumValue("\u04105")
    А_5("\u04105"),
    @XmlEnumValue("\u04106")
    А_6("\u04106"),
    @XmlEnumValue("\u04107")
    А_7("\u04107"),
    @XmlEnumValue("\u04108")
    А_8("\u04108"),
    @XmlEnumValue("\u04109")
    А_9("\u04109"),
    @XmlEnumValue("\u041010")
    А_10("\u041010"),
    @XmlEnumValue("\u041011.1")
    А_11_1("\u041011.1"),
    @XmlEnumValue("\u041011.2")
    А_11_2("\u041011.2"),
    @XmlEnumValue("\u041012.1")
    А_12_1("\u041012.1"),
    @XmlEnumValue("\u041012.2")
    А_12_2("\u041012.2"),
    @XmlEnumValue("\u041013")
    А_13("\u041013"),
    @XmlEnumValue("\u041014")
    А_14("\u041014"),
    @XmlEnumValue("\u041015")
    А_15("\u041015"),
    @XmlEnumValue("\u04111")
    Б_1("\u04111"),
    @XmlEnumValue("\u04112")
    Б_2("\u04112"),
    @XmlEnumValue("\u04113")
    Б_3("\u04113"),
    @XmlEnumValue("\u04114")
    Б_4("\u04114"),
    @XmlEnumValue("\u04115")
    Б_5("\u04115"),
    @XmlEnumValue("\u04116")
    Б_6("\u04116"),
    @XmlEnumValue("\u04117")
    Б_7("\u04117"),
    @XmlEnumValue("\u04118")
    Б_8("\u04118"),
    @XmlEnumValue("\u04119.1")
    Б_9_1("\u04119.1"),
    @XmlEnumValue("\u04119.2")
    Б_9_2("\u04119.2"),
    @XmlEnumValue("\u041110")
    Б_10("\u041110"),
    @XmlEnumValue("\u041110.1")
    Б_10_1("\u041110.1"),
    @XmlEnumValue("\u041110.2")
    Б_10_2("\u041110.2"),
    @XmlEnumValue("\u041111")
    Б_11("\u041111"),
    @XmlEnumValue("\u041112")
    Б_12("\u041112"),
    @XmlEnumValue("\u04121")
    В_1("\u04121"),
    @XmlEnumValue("\u04122")
    В_2("\u04122"),
    @XmlEnumValue("\u04123")
    В_3("\u04123"),
    @XmlEnumValue("\u04124")
    В_4("\u04124"),
    @XmlEnumValue("\u04125")
    В_5("\u04125"),
    @XmlEnumValue("\u04126")
    В_6("\u04126"),
    @XmlEnumValue("\u04127")
    В_7("\u04127"),
    @XmlEnumValue("\u04128")
    В_8("\u04128"),
    @XmlEnumValue("\u04129")
    В_9("\u04129"),
    @XmlEnumValue("\u041210.1")
    В_10_1("\u041210.1"),
    @XmlEnumValue("\u041210.2")
    В_10_2("\u041210.2"),
    @XmlEnumValue("\u041212")
    В_12("\u041212"),
    @XmlEnumValue("\u041213")
    В_13("\u041213"),
    @XmlEnumValue("\u041214")
    В_14("\u041214"),
    @XmlEnumValue("\u041215")
    В_15("\u041215"),
    @XmlEnumValue("\u04131")
    Г_1("\u04131"),
    @XmlEnumValue("\u04132")
    Г_2("\u04132"),
    @XmlEnumValue("\u04133")
    Г_3("\u04133"),
    @XmlEnumValue("\u04134")
    Г_4("\u04134"),
    @XmlEnumValue("\u04135")
    Г_5("\u04135"),
    @XmlEnumValue("\u04136")
    Г_6("\u04136"),
    @XmlEnumValue("\u04137")
    Г_7("\u04137"),
    @XmlEnumValue("\u04138.1")
    Г_8_1("\u04138.1"),
    @XmlEnumValue("\u04138.2")
    Г_8_2("\u04138.2"),
    @XmlEnumValue("\u04139")
    Г_9("\u04139"),
    @XmlEnumValue("\u041310")
    Г_10("\u041310"),
    @XmlEnumValue("\u04901")
    Ґ_1("\u04901"),
    @XmlEnumValue("\u04141.1")
    Д_1_1("\u04141.1"),
    @XmlEnumValue("\u04141.2")
    Д_1_2("\u04141.2"),
    @XmlEnumValue("\u04142.1")
    Д_2_1("\u04142.1"),
    @XmlEnumValue("\u04142.2")
    Д_2_2("\u04142.2");
    private final String value;

    DGJ02095Ind4(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DGJ02095Ind4 fromValue(String v) {
        for (DGJ02095Ind4 c: DGJ02095Ind4 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
