//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DGKodDocROVPD3_1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DGKodDocROVPD3_1">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ПН"/>
 *     &lt;enumeration value="РК"/>
 *     &lt;enumeration value="ВМД"/>
 *     &lt;enumeration value="ЧК"/>
 *     &lt;enumeration value="ТК"/>
 *     &lt;enumeration value="ГР"/>
 *     &lt;enumeration value="ПЗ"/>
 *     &lt;enumeration value="ПО"/>
 *     &lt;enumeration value="ЗП"/>
 *     &lt;enumeration value="ПНУ"/>
 *     &lt;enumeration value="РКУ"/>
 *     &lt;enumeration value="ВМДУ"/>
 *     &lt;enumeration value="ЧКУ"/>
 *     &lt;enumeration value="ТКУ"/>
 *     &lt;enumeration value="ГРУ"/>
 *     &lt;enumeration value="ПЗУ"/>
 *     &lt;enumeration value="ПОУ"/>
 *     &lt;enumeration value="ЗПУ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DGKodDocROVPD3_1")
@XmlEnum
public enum DGKodDocROVPD31 {


    /**
     * 
     * 				ПН - податкова накладна
     * 			
     * 
     */
    ПН,

    /**
     * 
     * 				РК - розрахунок коригування до податкової накладної (розрахунок коригування кількісних і вартісних показників (додаток 2 до податкової накладної))
     * 			
     * 
     */
    РК,

    /**
     * 
     * 				ВМД - вантажна митна деклараці
     * 			
     * 
     */
    ВМД,

    /**
     * 
     * 				ЧК - товарний (касовий) чек
     * 			
     * 
     */
    ЧК,

    /**
     * 
     * 				ТК - транспортний квиток
     * 			
     * 
     */
    ТК,

    /**
     * 
     * 				ГР - готельний рахунок
     * 			
     * 
     */
    ГР,

    /**
     * 
     * 				ПЗ - рахунок за послуги зв'язку
     * 			
     * 
     */
    ПЗ,

    /**
     * 
     * 				ПО - послуги, вартість яких визначається за показниками приладів обліку
     * 			
     * 
     */
    ПО,

    /**
     * 
     * 				ЗП - заява платника відповідно до підпункту 7.2.6 пункту 7.2 статті 7 Закону
     * 			
     * 
     */
    ЗП,

    /**
     * 
     * 				ПНУ - податкова накладна [уточнення]
     * 			
     * 
     */
    ПНУ,

    /**
     * 
     * 				РКУ - розрахунок коригування до податкової накладної (розрахунок коригування кількісних і вартісних показників (додаток 2 до податкової накладної)) [уточнення]
     * 			
     * 
     */
    РКУ,

    /**
     * 
     * 				ВМДУ - вантажна митна декларація [уточнення]
     * 			
     * 
     */
    ВМДУ,

    /**
     * 
     * 				ЧКУ - товарний (касовий) чек [уточнення]
     * 			
     * 
     */
    ЧКУ,

    /**
     * 
     * 				ТКУ - транспортний квиток [уточнення]
     * 			
     * 
     */
    ТКУ,

    /**
     * 
     * 				ГРУ - готельний рахунок [уточнення]
     * 			
     * 
     */
    ГРУ,

    /**
     * 
     * 				ПЗУ - рахунок за послуги зв'язку [уточнення]
     * 			
     * 
     */
    ПЗУ,

    /**
     * 
     * 				ПОУ - послуги, вартість яких визначається за показниками приладів обліку [уточнення]
     * 			
     * 
     */
    ПОУ,

    /**
     * 
     * 				ЗПУ - заява платника відповідно до підпункту 7.2.6 пункту 7.2 статті 7 Закону [уточнення]
     * 			
     * 
     */
    ЗПУ;

    public String value() {
        return name();
    }

    public static DGKodDocROVPD31 fromValue(String v) {
        return valueOf(v);
    }

}
