//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for DGKodDocROVPD5_2Column complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DGKodDocROVPD5_2Column">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;>DGKodDocROVPD5_2">
 *       &lt;attribute name="ROWNUM" use="required" type="{}rowInt" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DGKodDocROVPD5_2Column", propOrder = {
    "value"
})
public class DGKodDocROVPD52Column {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "ROWNUM", required = true)
    protected int rownum;

    /**
     * 
     * 			Коди "Вид документа" (Розділ IІ. Отримані податкові накладні):
     * 			ПН - податкова накладна;
     * 			РК - розрахунок коригування до податкової накладної (додаток 2 до податкової накладної));
     * 			ВМД - вантажна митна декларація;
     * 			ЧК - касовий чек;
     * 			ТК - транспортний квиток;
     * 			ГР - готельний рахунок;
     * 			ПЗ - рахунок на послуги зв'язку;
     * 			ПО - послуги, вартість яких визначається за показниками приладів обліку;
     * 			ЗП - заява платника відповідно до пункту 201.10 статті 201 розділу V Кодексу;
     * 			НП - документ, що засвідчує придбання товарів/послуг на митній території України в осіб, які не зареєстровані як платники ПДВ;
     * 			БО - документ бухгалтерського обліку; Внесено згідно листа _______
     * 			До виду документа додається літера „Р” - якщо платником проводиться розподіл сум податкового кредиту відповідно до пункту 199.1 статті 199 та/або абзацу третього підпункту 209.15.1 пункту 209.15 статті 209 розділу V Кодексу;
     * 			У разі якщо дані документа включаються до уточнюючих розрахунків за звітний період, до виду документа додається літера "У"
     * 			
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the rownum property.
     * 
     */
    public int getROWNUM() {
        return rownum;
    }

    /**
     * Sets the value of the rownum property.
     * 
     */
    public void setROWNUM(int value) {
        this.rownum = value;
    }

}
