//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DGKodDocROVPD6_2.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DGKodDocROVPD6_2">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ПНП"/>
 *     &lt;enumeration value="ПНЕ"/>
 *     &lt;enumeration value="РКП"/>
 *     &lt;enumeration value="РКЕ"/>
 *     &lt;enumeration value="МДП"/>
 *     &lt;enumeration value="МДЕ"/>
 *     &lt;enumeration value="ЧК"/>
 *     &lt;enumeration value="ТК"/>
 *     &lt;enumeration value="ГР"/>
 *     &lt;enumeration value="ПЗ"/>
 *     &lt;enumeration value="ПО"/>
 *     &lt;enumeration value="ЗП"/>
 *     &lt;enumeration value="НП"/>
 *     &lt;enumeration value="БО"/>
 *     &lt;enumeration value="БОПНП"/>
 *     &lt;enumeration value="БОПНЕ"/>
 *     &lt;enumeration value="БОРКП"/>
 *     &lt;enumeration value="БОРКЕ"/>
 *     &lt;enumeration value="БОМДП"/>
 *     &lt;enumeration value="БОМДЕ"/>
 *     &lt;enumeration value="БОЧК"/>
 *     &lt;enumeration value="БОТК"/>
 *     &lt;enumeration value="БОГР"/>
 *     &lt;enumeration value="БОПЗ"/>
 *     &lt;enumeration value="БОПО"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DGKodDocROVPD6_2")
@XmlEnum
public enum DGKodDocROVPD62 {

    ПНП,
    ПНЕ,
    РКП,
    РКЕ,
    МДП,
    МДЕ,
    ЧК,
    ТК,
    ГР,
    ПЗ,
    ПО,
    ЗП,
    НП,
    БО,
    БОПНП,
    БОПНЕ,
    БОРКП,
    БОРКЕ,
    БОМДП,
    БОМДЕ,
    БОЧК,
    БОТК,
    БОГР,
    БОПЗ,
    БОПО;

    public String value() {
        return name();
    }

    public static DGKodDocROVPD62 fromValue(String v) {
        return valueOf(v);
    }

}
