//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for DGKodСausesOperation6Column complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DGKodСausesOperation6Column">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;>DGKodСausesOperation6">
 *       &lt;attribute name="ROWNUM" use="required" type="{}rowInt" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DGKodCausesOperation6Column", propOrder = {
    "value"
})
public class DGKodCausesOperation6Column {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "ROWNUM", required = true)
    protected int rownum;

    /**
     * 
     * 			Причини, складання податкової накладної за окремими операціями для Розділ I та для Розділ II
     * 			01 – Складена на суму перевищення звичайної ціни над фактичною; 
     * 			02 – Постачання неплатнику податку; 
     * 			03 – Постачання товарів/послуг у рахунок оплати праці фізичним особам, які перебувають у трудових відносинах із платником податку; 
     * 			04 – Постачання у межах балансу для невиробничого використання; 
     * 			05 – Ліквідація основних засобів за самостійним рішенням платника податку;
     * 			06 – Переведення виробничих основних засобів до складу невиробничих;
     * 			07 – Експортні постачання;
     * 			08 – Постачання для операцій, які не є об'єктом оподаткування податком на додану вартість;
     * 			09 – Постачання для операцій, які звільнені від оподаткування податком на додану вартість;
     * 			10 – Визначення при анулюванні платника податку податкових зобов'язань по товарах/послугах, необоротних активах, суми податку по яких були включені до складу податкового кредиту, не були використані в оподатковуваних операціях у межах господарської діяльності;
     * 			11 – Складена за щоденними підсумками операцій;
     * 			12 – Складена на вартість безоплатно поставлених товарів/послуг, обчислену виходячи з рівня звичайних цін;
     * 			13 – Використання виробничих або невиробничих засобів, інших товарів/послуг не у господарській діяльності;
     * 			14 – Складена покупцем (отримувачем) послуг від нерезидента.
     * 			15 – Складена на суму перевищення митної вартості над фактичною ціною постачання.
     * 			16 – Складена на суму перевищення балансової (залишкової) вартості необоротних активів над фактичною ціною їх постачання.
     * 			17 - складена на суму перевищення собівартості самостійно виготовлених товарів/послуг над фактичною ціною їх постачання.
     * 			
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the rownum property.
     * 
     */
    public int getROWNUM() {
        return rownum;
    }

    /**
     * Sets the value of the rownum property.
     * 
     */
    public void setROWNUM(int value) {
        this.rownum = value;
    }

}
