//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for DGKodDocROVPD6_2Column complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DGKodDocROVPD6_2Column">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;>DGKodDocROVPD6_2">
 *       &lt;attribute name="ROWNUM" use="required" type="{}rowInt" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DGKodDocROVPD6_2Column", propOrder = {
    "value"
})
public class DGKodDocROVPD62Column {

    @XmlValue
    protected DGKodDocROVPD62 value;
    @XmlAttribute(name = "ROWNUM", required = true)
    protected int rownum;

    /**
     * 
     * 			Види документів для Розділ ІІ Реєстру
     * 			ПНП – податкова накладна, складена на паперових носіях;
     * 			ПНЕ  – електронна податкова накладна; 
     * 			РКП – розрахунок коригування кількісних і вартісних показників до податкової накладної (додаток 2 до податкової накладної), складений на паперових носіях; 
     * 			РКЕ – електронний розрахунок коригування кількісних і вартісних показників до податкової накладної (додаток 2 до податкової накладної); 
     * 			МДП – митна декларація, складена на паперових носіях;
     * 			МДЕ – електронна митна декларація; 
     * 			ЧК – касовий чек. 
     * 			ТК – транспортний квиток; 
     * 			ГР – готельний рахунок; 
     * 			ПЗ – рахунок за послуги зв’язку; 
     * 			ПО – послуги, вартість яких визначається за показниками приладів обліку; 
     * 			ЗП – заява платника та копії товарних чеків або інших розрахункових документів, що засвідчують факт сплати податку у зв’язку з придбанням таких товарів/послуг, або копії первинних документів, складених відповідно до Закону України „Про бухгалтерський облік та фінансову звітність в Україні”, що підтверджують факт отримання таких товарів/послуг відповідно до		  пункту 201.10 статті 201 розділу V Кодексу;
     * 			НП – документ, що засвідчує придбання товарів/послуг на митній території України в осіб, які не зареєстровані як платники податку на додану вартість;
     * 			БО – документ бухгалтерського обліку, в тому числі бухгалтерська довідка
     * 			
     * 			БОПНП – документ бухгалтерського обліку, яким підтверджується операція з постачання на основі податкової накладної, що складена на паперових носіях;
     * 			БОПНЕ – документ бухгалтерського обліку, яким підтверджується операція з постачання на основі електронної податкової накладної; 
     * 			БОРКП – документ бухгалтерського обліку, яким підтверджується операція з постачання на основі розрахунку коригування кількісних і вартісних показників до податкової накладної (додаток 2 до податкової накладної), складений на паперових носіях; 
     * 			БОРКЕ – документ бухгалтерського обліку, яким підтверджується операція з постачання на основі електронного розрахуноку коригування кількісних і вартісних показників до податкової накладної (додаток 2 до податкової накладної); 
     * 			БОМДП – документ бухгалтерського обліку, яким підтверджується операція з постачання на основі митної декларації, складеної на паперових носіях;
     * 			БОМДЕ – документ бухгалтерського обліку, яким підтверджується операція з постачання на основі електронної митної декларації; 
     * 			БОЧК – документ бухгалтерського обліку, яким підтверджується операція з постачання на основі касового чеку. 
     * 			БОТК – документ бухгалтерського обліку, яким підтверджується операція з постачання на основі транспортного квитка; 
     * 			БОГР – документ бухгалтерського обліку, яким підтверджується операція з постачання на основі готельного рахунку; 
     * 			БОПЗ – документ бухгалтерського обліку, яким підтверджується операція з постачання на основі рахунку за послуги зв’язку; 
     * 			БОПО – документ бухгалтерського обліку, яким підтверджується операція з постачання на основі послуги, вартість яких визначається за показниками приладів обліку; 
     * 			
     * 
     * @return
     *     possible object is
     *     {@link DGKodDocROVPD62 }
     *     
     */
    public DGKodDocROVPD62 getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link DGKodDocROVPD62 }
     *     
     */
    public void setValue(DGKodDocROVPD62 value) {
        this.value = value;
    }

    /**
     * Gets the value of the rownum property.
     * 
     */
    public int getROWNUM() {
        return rownum;
    }

    /**
     * Sets the value of the rownum property.
     * 
     */
    public void setROWNUM(int value) {
        this.rownum = value;
    }

}
