//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DGSign.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DGSign">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Директор"/>
 *     &lt;enumeration value="Бухгалтер"/>
 *     &lt;enumeration value="Підпис податкових накладних"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DGSign")
@XmlEnum
public enum DGSign {

    @XmlEnumValue("\u0414\u0438\u0440\u0435\u043a\u0442\u043e\u0440")
    ДИРЕКТОР("\u0414\u0438\u0440\u0435\u043a\u0442\u043e\u0440"),
    @XmlEnumValue("\u0411\u0443\u0445\u0433\u0430\u043b\u0442\u0435\u0440")
    БУХГАЛТЕР("\u0411\u0443\u0445\u0433\u0430\u043b\u0442\u0435\u0440"),
    @XmlEnumValue("\u041f\u0456\u0434\u043f\u0438\u0441 \u043f\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0438\u0445 \u043d\u0430\u043a\u043b\u0430\u0434\u043d\u0438\u0445")
    ПІДПИС_ПОДАТКОВИХ_НАКЛАДНИХ("\u041f\u0456\u0434\u043f\u0438\u0441 \u043f\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0438\u0445 \u043d\u0430\u043a\u043b\u0430\u0434\u043d\u0438\u0445");
    private final String value;

    DGSign(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DGSign fromValue(String v) {
        for (DGSign c: DGSign.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
