//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DHead complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DHead">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TIN" type="{}DGLong"/>
 *         &lt;element name="C_DOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="C_DOC_SUB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="C_DOC_VER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="C_DOC_TYPE" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="C_DOC_CNT" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="C_REG" type="{}DGsti"/>
 *         &lt;element name="C_RAJ" type="{}DGsti"/>
 *         &lt;element name="PERIOD_MONTH" type="{}DGMonth"/>
 *         &lt;element name="PERIOD_TYPE" type="{}DGPType"/>
 *         &lt;element name="PERIOD_YEAR" type="{}DGYear"/>
 *         &lt;element name="C_STI_ORIG" type="{}DGc_dpi"/>
 *         &lt;element name="C_DOC_STAN" type="{}DGSTAN"/>
 *         &lt;element name="LINKED_DOCS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DOC" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="C_DOC" type="{}DGC_DOC"/>
 *                             &lt;element name="C_DOC_SUB" type="{}DGC_DOC_SUB"/>
 *                             &lt;element name="C_DOC_VER" type="{}DGC_DOC_VER"/>
 *                             &lt;element name="C_DOC_TYPE" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                             &lt;element name="C_DOC_CNT" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                             &lt;element name="C_DOC_STAN" type="{}DGSTAN"/>
 *                             &lt;element name="FILENAME" type="{}DGFilename"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="NUM" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="TYPE" type="{}DGTypeLinkDoc" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="D_FILL" type="{}DGDate"/>
 *         &lt;element name="SOFTWARE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DHead", propOrder = {
    "tin",
    "cdoc",
    "cdocsub",
    "cdocver",
    "cdoctype",
    "cdoccnt",
    "creg",
    "craj",
    "periodmonth",
    "periodtype",
    "periodyear",
    "cstiorig",
    "cdocstan",
    "linkeddocs",
    "dfill",
    "software"
})
public class DHead {

    @XmlElement(name = "TIN", required = true)
    protected String tin;
    @XmlElement(name = "C_DOC", required = true)
    protected String cdoc;
    @XmlElement(name = "C_DOC_SUB", required = true)
    protected String cdocsub;
    @XmlElement(name = "C_DOC_VER", required = true)
    protected String cdocver;
    @XmlElement(name = "C_DOC_TYPE", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger cdoctype;
    @XmlElement(name = "C_DOC_CNT", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger cdoccnt;
    @XmlElement(name = "C_REG")
    protected Integer creg;
    @XmlElement(name = "C_RAJ")
    protected Integer craj;
    @XmlElement(name = "PERIOD_MONTH")
    protected Integer periodmonth;
    @XmlElement(name = "PERIOD_TYPE")
    protected Integer periodtype;
    @XmlElement(name = "PERIOD_YEAR")
    protected Integer periodyear;
    @XmlElement(name = "C_STI_ORIG")
    protected Integer cstiorig;
    @XmlElement(name = "C_DOC_STAN")
    protected Integer cdocstan;
    @XmlElementRef(name = "LINKED_DOCS", type = JAXBElement.class, required = false)
    protected JAXBElement<DHead.LINKEDDOCS> linkeddocs;
    @XmlElement(name = "D_FILL", required = true)
    protected String dfill;
    @XmlElementRef(name = "SOFTWARE", type = JAXBElement.class, required = false)
    protected JAXBElement<String> software;

    /**
     * Gets the value of the tin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIN() {
        return tin;
    }

    /**
     * Sets the value of the tin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIN(String value) {
        this.tin = value;
    }

    /**
     * Gets the value of the cdoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDOC() {
        return cdoc;
    }

    /**
     * Sets the value of the cdoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDOC(String value) {
        this.cdoc = value;
    }

    /**
     * Gets the value of the cdocsub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDOCSUB() {
        return cdocsub;
    }

    /**
     * Sets the value of the cdocsub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDOCSUB(String value) {
        this.cdocsub = value;
    }

    /**
     * Gets the value of the cdocver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDOCVER() {
        return cdocver;
    }

    /**
     * Sets the value of the cdocver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDOCVER(String value) {
        this.cdocver = value;
    }

    /**
     * Gets the value of the cdoctype property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCDOCTYPE() {
        return cdoctype;
    }

    /**
     * Sets the value of the cdoctype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCDOCTYPE(BigInteger value) {
        this.cdoctype = value;
    }

    /**
     * Gets the value of the cdoccnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCDOCCNT() {
        return cdoccnt;
    }

    /**
     * Sets the value of the cdoccnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCDOCCNT(BigInteger value) {
        this.cdoccnt = value;
    }

    /**
     * Gets the value of the creg property.
     * 
     */
    public int getCREG() {
        return creg;
    }

    /**
     * Sets the value of the creg property.
     * 
     */
    public void setCREG(Integer value) {
        this.creg = value;
    }

    /**
     * Gets the value of the craj property.
     * 
     */
    public int getCRAJ() {
        return craj;
    }

    /**
     * Sets the value of the craj property.
     * 
     */
    public void setCRAJ(Integer value) {
        this.craj = value;
    }

    /**
     * Gets the value of the periodmonth property.
     * 
     */
    public int getPERIODMONTH() {
        return periodmonth;
    }

    /**
     * Sets the value of the periodmonth property.
     * 
     */
    public void setPERIODMONTH(Integer value) {
        this.periodmonth = value;
    }

    /**
     * Gets the value of the periodtype property.
     * 
     */
    public int getPERIODTYPE() {
        return periodtype;
    }

    /**
     * Sets the value of the periodtype property.
     * 
     */
    public void setPERIODTYPE(Integer value) {
        this.periodtype = value;
    }

    /**
     * Gets the value of the periodyear property.
     * 
     */
    public int getPERIODYEAR() {
        return periodyear;
    }

    /**
     * Sets the value of the periodyear property.
     * 
     */
    public void setPERIODYEAR(Integer value) {
        this.periodyear = value;
    }

    /**
     * Gets the value of the cstiorig property.
     * 
     */
    public int getCSTIORIG() {
        return cstiorig;
    }

    /**
     * Sets the value of the cstiorig property.
     * 
     */
    public void setCSTIORIG(Integer value) {
        this.cstiorig = value;
    }

    /**
     * Gets the value of the cdocstan property.
     * 
     */
    public int getCDOCSTAN() {
        return cdocstan;
    }

    /**
     * Sets the value of the cdocstan property.
     * 
     */
    public void setCDOCSTAN(Integer value) {
        this.cdocstan = value;
    }

    /**
     * Gets the value of the linkeddocs property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DHead.LINKEDDOCS }{@code >}
     *     
     */
    public JAXBElement<DHead.LINKEDDOCS> getLINKEDDOCS() {
        return linkeddocs;
    }

    /**
     * Sets the value of the linkeddocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DHead.LINKEDDOCS }{@code >}
     *     
     */
    public void setLINKEDDOCS(JAXBElement<DHead.LINKEDDOCS> value) {
        this.linkeddocs = value;
    }

    /**
     * Gets the value of the dfill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFILL() {
        return dfill;
    }

    /**
     * Sets the value of the dfill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFILL(String value) {
        this.dfill = value;
    }

    /**
     * Gets the value of the software property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSOFTWARE() {
        return software;
    }

    /**
     * Sets the value of the software property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSOFTWARE(JAXBElement<String> value) {
        this.software = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DOC" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="C_DOC" type="{}DGC_DOC"/>
     *                   &lt;element name="C_DOC_SUB" type="{}DGC_DOC_SUB"/>
     *                   &lt;element name="C_DOC_VER" type="{}DGC_DOC_VER"/>
     *                   &lt;element name="C_DOC_TYPE" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *                   &lt;element name="C_DOC_CNT" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *                   &lt;element name="C_DOC_STAN" type="{}DGSTAN"/>
     *                   &lt;element name="FILENAME" type="{}DGFilename"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="NUM" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="TYPE" type="{}DGTypeLinkDoc" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "doc"
    })
    public static class LINKEDDOCS {

        @XmlElement(name = "DOC", required = true)
        protected List<DHead.LINKEDDOCS.DOC> doc;

        /**
         * Gets the value of the doc property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the doc property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDOC().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DHead.LINKEDDOCS.DOC }
         * 
         * 
         */
        public List<DHead.LINKEDDOCS.DOC> getDOC() {
            if (doc == null) {
                doc = new ArrayList<DHead.LINKEDDOCS.DOC>();
            }
            return this.doc;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="C_DOC" type="{}DGC_DOC"/>
         *         &lt;element name="C_DOC_SUB" type="{}DGC_DOC_SUB"/>
         *         &lt;element name="C_DOC_VER" type="{}DGC_DOC_VER"/>
         *         &lt;element name="C_DOC_TYPE" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
         *         &lt;element name="C_DOC_CNT" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
         *         &lt;element name="C_DOC_STAN" type="{}DGSTAN"/>
         *         &lt;element name="FILENAME" type="{}DGFilename"/>
         *       &lt;/sequence>
         *       &lt;attribute name="NUM" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="TYPE" type="{}DGTypeLinkDoc" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cdoc",
            "cdocsub",
            "cdocver",
            "cdoctype",
            "cdoccnt",
            "cdocstan",
            "filename"
        })
        public static class DOC {

            @XmlElement(name = "C_DOC", required = true)
            protected String cdoc;
            @XmlElement(name = "C_DOC_SUB", required = true)
            protected String cdocsub;
            @XmlElement(name = "C_DOC_VER", required = true)
            protected String cdocver;
            @XmlElement(name = "C_DOC_TYPE", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger cdoctype;
            @XmlElement(name = "C_DOC_CNT", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger cdoccnt;
            @XmlElement(name = "C_DOC_STAN")
            protected int cdocstan;
            @XmlElement(name = "FILENAME", required = true)
            protected String filename;
            @XmlAttribute(name = "NUM")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger num;
            @XmlAttribute(name = "TYPE")
            protected BigInteger type;

            /**
             * Gets the value of the cdoc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCDOC() {
                return cdoc;
            }

            /**
             * Sets the value of the cdoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCDOC(String value) {
                this.cdoc = value;
            }

            /**
             * Gets the value of the cdocsub property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCDOCSUB() {
                return cdocsub;
            }

            /**
             * Sets the value of the cdocsub property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCDOCSUB(String value) {
                this.cdocsub = value;
            }

            /**
             * Gets the value of the cdocver property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCDOCVER() {
                return cdocver;
            }

            /**
             * Sets the value of the cdocver property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCDOCVER(String value) {
                this.cdocver = value;
            }

            /**
             * Gets the value of the cdoctype property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCDOCTYPE() {
                return cdoctype;
            }

            /**
             * Sets the value of the cdoctype property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCDOCTYPE(BigInteger value) {
                this.cdoctype = value;
            }

            /**
             * Gets the value of the cdoccnt property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCDOCCNT() {
                return cdoccnt;
            }

            /**
             * Sets the value of the cdoccnt property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCDOCCNT(BigInteger value) {
                this.cdoccnt = value;
            }

            /**
             * Gets the value of the cdocstan property.
             * 
             */
            public int getCDOCSTAN() {
                return cdocstan;
            }

            /**
             * Sets the value of the cdocstan property.
             * 
             */
            public void setCDOCSTAN(int value) {
                this.cdocstan = value;
            }

            /**
             * Gets the value of the filename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFILENAME() {
                return filename;
            }

            /**
             * Sets the value of the filename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFILENAME(String value) {
                this.filename = value;
            }

            /**
             * Gets the value of the num property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNUM() {
                return num;
            }

            /**
             * Sets the value of the num property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNUM(BigInteger value) {
                this.num = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTYPE() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTYPE(BigInteger value) {
                this.type = value;
            }

        }

    }

}
