//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for KNEAColumn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KNEAColumn">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;>DGKNEA">
 *       &lt;attribute name="ROWNUM" use="required" type="{}rowInt" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KNEAColumn", propOrder = {
    "value"
})
public class KNEAColumn {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "ROWNUM", required = true)
    protected int rownum;

    /**
     * 
     * 			Кадастровий номер земельної ділянки складається з таких структурних елементів:
     * 			НКЗ : НКК : НЗД,
     * 			де НКЗ - номер кадастрової зони
     * 				НКК - номер кадастрового кварталу
     * 			Номер кадастрового кварталу складається з таких структурних елементів:
     * 			НКЗ : НКК,
     * 			де НКЗ - дванадцятизначний номер кадастрової зони (максимальна кількість кадастрових зон становить 999999999999), в якому останні дві цифри відокремлюються від перших десяти двокрапкою;
     * 			НКК - тризначний номер кадастрового кварталу в межах кадастрової зони (максимальна кількість кадастрових кварталів у межах кадастрової зони становить 999).
     * 			Для нумерації кадастрової зони за межами адміністративно-територіальних одиниць використовується значення 9000000000 : 00.
     * 			НЗД - чотиризначний номер земельної ділянки в межах кадастрового кварталу (максимальна кількість земельних ділянок у межах кадастрового кварталу становить 9999)
     * 			Структурні елементи кадастрового номера земельної ділянки відокремлюються один від одного двокрапкою (:).
     *    
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the rownum property.
     * 
     */
    public int getROWNUM() {
        return rownum;
    }

    /**
     * Sets the value of the rownum property.
     * 
     */
    public void setROWNUM(int value) {
        this.rownum = value;
    }

}
