//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 04:30:25 PM EEST 
//


package org.igov.util.swind.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.igov.util.swind.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DECLAR_QNAME = new QName("", "DECLAR");
    private final static QName _DHeadLINKEDDOCS_QNAME = new QName("", "LINKED_DOCS");
    private final static QName _DHeadSOFTWARE_QNAME = new QName("", "SOFTWARE");
    private final static QName _DBodyHPASSISS_QNAME = new QName("", "HPASSISS");
    private final static QName _DBodyHSHOT_QNAME = new QName("", "HSHOT");
    private final static QName _DBodyHREG_QNAME = new QName("", "HREG");
    private final static QName _DBodyHFNAME_QNAME = new QName("", "HFNAME");
    private final static QName _DBodyHPASSDATE_QNAME = new QName("", "HPASSDATE");
    private final static QName _DBodyHAPT_QNAME = new QName("", "HAPT");
    private final static QName _DBodyHRAJ_QNAME = new QName("", "HRAJ");
    private final static QName _DBodyHPASS_QNAME = new QName("", "HPASS");
    private final static QName _DBodyHCORP_QNAME = new QName("", "HCORP");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.igov.util.swind.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DHead }
     * 
     */
    public DHead createDHead() {
        return new DHead();
    }

    /**
     * Create an instance of {@link DHead.LINKEDDOCS }
     * 
     */
    public DHead.LINKEDDOCS createDHeadLINKEDDOCS() {
        return new DHead.LINKEDDOCS();
    }

    /**
     * Create an instance of {@link DeclarContent }
     * 
     */
    public DeclarContent createDeclarContent() {
        return new DeclarContent();
    }

    /**
     * Create an instance of {@link KvColumn }
     * 
     */
    public KvColumn createKvColumn() {
        return new KvColumn();
    }

    /**
     * Create an instance of {@link Decimal5Column }
     * 
     */
    public Decimal5Column createDecimal5Column() {
        return new Decimal5Column();
    }

    /**
     * Create an instance of {@link Decimal1Column }
     * 
     */
    public Decimal1Column createDecimal1Column() {
        return new Decimal1Column();
    }

    /**
     * Create an instance of {@link In03Column }
     * 
     */
    public In03Column createIn03Column() {
        return new In03Column();
    }

    /**
     * Create an instance of {@link TOColumn }
     * 
     */
    public TOColumn createTOColumn() {
        return new TOColumn();
    }

    /**
     * Create an instance of {@link OdohColumn }
     * 
     */
    public OdohColumn createOdohColumn() {
        return new OdohColumn();
    }

    /**
     * Create an instance of {@link DGLong12Column }
     * 
     */
    public DGLong12Column createDGLong12Column() {
        return new DGLong12Column();
    }

    /**
     * Create an instance of {@link PassNumColumn }
     * 
     */
    public PassNumColumn createPassNumColumn() {
        return new PassNumColumn();
    }

    /**
     * Create an instance of {@link KNEAColumn }
     * 
     */
    public KNEAColumn createKNEAColumn() {
        return new KNEAColumn();
    }

    /**
     * Create an instance of {@link DKPP0Column }
     * 
     */
    public DKPP0Column createDKPP0Column() {
        return new DKPP0Column();
    }

    /**
     * Create an instance of {@link SDSPperiodEndColumn }
     * 
     */
    public SDSPperiodEndColumn createSDSPperiodEndColumn() {
        return new SDSPperiodEndColumn();
    }

    /**
     * Create an instance of {@link N2PointN2Column }
     * 
     */
    public N2PointN2Column createN2PointN2Column() {
        return new N2PointN2Column();
    }

    /**
     * Create an instance of {@link I8Column }
     * 
     */
    public I8Column createI8Column() {
        return new I8Column();
    }

    /**
     * Create an instance of {@link DGcpVOColumn }
     * 
     */
    public DGcpVOColumn createDGcpVOColumn() {
        return new DGcpVOColumn();
    }

    /**
     * Create an instance of {@link Ozn2Column }
     * 
     */
    public Ozn2Column createOzn2Column() {
        return new Ozn2Column();
    }

    /**
     * Create an instance of {@link DGI7NomColumn }
     * 
     */
    public DGI7NomColumn createDGI7NomColumn() {
        return new DGI7NomColumn();
    }

    /**
     * Create an instance of {@link IntNegativeColumn }
     * 
     */
    public IntNegativeColumn createIntNegativeColumn() {
        return new IntNegativeColumn();
    }

    /**
     * Create an instance of {@link DGKodDocROVPD62Column }
     * 
     */
    public DGKodDocROVPD62Column createDGKodDocROVPD62Column() {
        return new DGKodDocROVPD62Column();
    }

    /**
     * Create an instance of {@link SeazonColumn }
     * 
     */
    public SeazonColumn createSeazonColumn() {
        return new SeazonColumn();
    }

    /**
     * Create an instance of {@link I2InomColumn }
     * 
     */
    public I2InomColumn createI2InomColumn() {
        return new I2InomColumn();
    }

    /**
     * Create an instance of {@link PassSerColumn }
     * 
     */
    public PassSerColumn createPassSerColumn() {
        return new PassSerColumn();
    }

    /**
     * Create an instance of {@link DRFO10Column }
     * 
     */
    public DRFO10Column createDRFO10Column() {
        return new DRFO10Column();
    }

    /**
     * Create an instance of {@link ZipColumn }
     * 
     */
    public ZipColumn createZipColumn() {
        return new ZipColumn();
    }

    /**
     * Create an instance of {@link DGKodRectification6Column }
     * 
     */
    public DGKodRectification6Column createDGKodRectification6Column() {
        return new DGKodRectification6Column();
    }

    /**
     * Create an instance of {@link NumZOColumn }
     * 
     */
    public NumZOColumn createNumZOColumn() {
        return new NumZOColumn();
    }

    /**
     * Create an instance of {@link HIPNColumn0 }
     * 
     */
    public HIPNColumn0 createHIPNColumn0() {
        return new HIPNColumn0();
    }

    /**
     * Create an instance of {@link DGcpPBRColumn }
     * 
     */
    public DGcpPBRColumn createDGcpPBRColumn() {
        return new DGcpPBRColumn();
    }

    /**
     * Create an instance of {@link Decimal6ColumnR }
     * 
     */
    public Decimal6ColumnR createDecimal6ColumnR() {
        return new Decimal6ColumnR();
    }

    /**
     * Create an instance of {@link DGkvedColumn }
     * 
     */
    public DGkvedColumn createDGkvedColumn() {
        return new DGkvedColumn();
    }

    /**
     * Create an instance of {@link Oplg1DFColumn }
     * 
     */
    public Oplg1DFColumn createOplg1DFColumn() {
        return new Oplg1DFColumn();
    }

    /**
     * Create an instance of {@link DMColumn }
     * 
     */
    public DMColumn createDMColumn() {
        return new DMColumn();
    }

    /**
     * Create an instance of {@link MfoColumn }
     * 
     */
    public MfoColumn createMfoColumn() {
        return new MfoColumn();
    }

    /**
     * Create an instance of {@link UKTZEDColumn }
     * 
     */
    public UKTZEDColumn createUKTZEDColumn() {
        return new UKTZEDColumn();
    }

    /**
     * Create an instance of {@link DGKodDocROVPD52Column }
     * 
     */
    public DGKodDocROVPD52Column createDGKodDocROVPD52Column() {
        return new DGKodDocROVPD52Column();
    }

    /**
     * Create an instance of {@link DGInomColumn }
     * 
     */
    public DGInomColumn createDGInomColumn() {
        return new DGInomColumn();
    }

    /**
     * Create an instance of {@link TnZedColumn }
     * 
     */
    public TnZedColumn createTnZedColumn() {
        return new TnZedColumn();
    }

    /**
     * Create an instance of {@link KOATUUColumn }
     * 
     */
    public KOATUUColumn createKOATUUColumn() {
        return new KOATUUColumn();
    }

    /**
     * Create an instance of {@link MonthColumn }
     * 
     */
    public MonthColumn createMonthColumn() {
        return new MonthColumn();
    }

    /**
     * Create an instance of {@link StrHandleColumn }
     * 
     */
    public StrHandleColumn createStrHandleColumn() {
        return new StrHandleColumn();
    }

    /**
     * Create an instance of {@link DecimalColumn }
     * 
     */
    public DecimalColumn createDecimalColumn() {
        return new DecimalColumn();
    }

    /**
     * Create an instance of {@link StatusColumn }
     * 
     */
    public StatusColumn createStatusColumn() {
        return new StatusColumn();
    }

    /**
     * Create an instance of {@link Decimal6Column }
     * 
     */
    public Decimal6Column createDecimal6Column() {
        return new Decimal6Column();
    }

    /**
     * Create an instance of {@link DGcpCFIColumn }
     * 
     */
    public DGcpCFIColumn createDGcpCFIColumn() {
        return new DGcpCFIColumn();
    }

    /**
     * Create an instance of {@link DGkzep0Column }
     * 
     */
    public DGkzep0Column createDGkzep0Column() {
        return new DGkzep0Column();
    }

    /**
     * Create an instance of {@link Decimal4Column }
     * 
     */
    public Decimal4Column createDecimal4Column() {
        return new Decimal4Column();
    }

    /**
     * Create an instance of {@link DGcpTDCPColumn }
     * 
     */
    public DGcpTDCPColumn createDGcpTDCPColumn() {
        return new DGcpTDCPColumn();
    }

    /**
     * Create an instance of {@link Odoh1DFColumn }
     * 
     */
    public Odoh1DFColumn createOdoh1DFColumn() {
        return new Odoh1DFColumn();
    }

    /**
     * Create an instance of {@link DGKodControlledOperationTB08Column }
     * 
     */
    public DGKodControlledOperationTB08Column createDGKodControlledOperationTB08Column() {
        return new DGKodControlledOperationTB08Column();
    }

    /**
     * Create an instance of {@link OspColumn }
     * 
     */
    public OspColumn createOspColumn() {
        return new OspColumn();
    }

    /**
     * Create an instance of {@link DGI1NomColumn }
     * 
     */
    public DGI1NomColumn createDGI1NomColumn() {
        return new DGI1NomColumn();
    }

    /**
     * Create an instance of {@link DGMonthYearColumn }
     * 
     */
    public DGMonthYearColumn createDGMonthYearColumn() {
        return new DGMonthYearColumn();
    }

    /**
     * Create an instance of {@link Decimal2ColumnP }
     * 
     */
    public Decimal2ColumnP createDecimal2ColumnP() {
        return new Decimal2ColumnP();
    }

    /**
     * Create an instance of {@link ChkColumn }
     * 
     */
    public ChkColumn createChkColumn() {
        return new ChkColumn();
    }

    /**
     * Create an instance of {@link KodColumn }
     * 
     */
    public KodColumn createKodColumn() {
        return new KodColumn();
    }

    /**
     * Create an instance of {@link Decimal13ColumnR }
     * 
     */
    public Decimal13ColumnR createDecimal13ColumnR() {
        return new Decimal13ColumnR();
    }

    /**
     * Create an instance of {@link YearColumn }
     * 
     */
    public YearColumn createYearColumn() {
        return new YearColumn();
    }

    /**
     * Create an instance of {@link DGKodDocROVPD51Column }
     * 
     */
    public DGKodDocROVPD51Column createDGKodDocROVPD51Column() {
        return new DGKodDocROVPD51Column();
    }

    /**
     * Create an instance of {@link DGJ13001TypeDocColumn }
     * 
     */
    public DGJ13001TypeDocColumn createDGJ13001TypeDocColumn() {
        return new DGJ13001TypeDocColumn();
    }

    /**
     * Create an instance of {@link RegColumn }
     * 
     */
    public RegColumn createRegColumn() {
        return new RegColumn();
    }

    /**
     * Create an instance of {@link OznColumn }
     * 
     */
    public OznColumn createOznColumn() {
        return new OznColumn();
    }

    /**
     * Create an instance of {@link DGcpFPRColumn }
     * 
     */
    public DGcpFPRColumn createDGcpFPRColumn() {
        return new DGcpFPRColumn();
    }

    /**
     * Create an instance of {@link In15Column }
     * 
     */
    public In15Column createIn15Column() {
        return new In15Column();
    }

    /**
     * Create an instance of {@link DBody }
     * 
     */
    public DBody createDBody() {
        return new DBody();
    }

    /**
     * Create an instance of {@link TinColumn }
     * 
     */
    public TinColumn createTinColumn() {
        return new TinColumn();
    }

    /**
     * Create an instance of {@link Decimal3Column }
     * 
     */
    public Decimal3Column createDecimal3Column() {
        return new Decimal3Column();
    }

    /**
     * Create an instance of {@link DGSignGKSColumn }
     * 
     */
    public DGSignGKSColumn createDGSignGKSColumn() {
        return new DGSignGKSColumn();
    }

    /**
     * Create an instance of {@link SDSPperiodBegColumn }
     * 
     */
    public SDSPperiodBegColumn createSDSPperiodBegColumn() {
        return new SDSPperiodBegColumn();
    }

    /**
     * Create an instance of {@link SDSPresultProcColumn }
     * 
     */
    public SDSPresultProcColumn createSDSPresultProcColumn() {
        return new SDSPresultProcColumn();
    }

    /**
     * Create an instance of {@link DGspecNomColumn }
     * 
     */
    public DGspecNomColumn createDGspecNomColumn() {
        return new DGspecNomColumn();
    }

    /**
     * Create an instance of {@link DateColumn }
     * 
     */
    public DateColumn createDateColumn() {
        return new DateColumn();
    }

    /**
     * Create an instance of {@link KodDocROVPD32Column }
     * 
     */
    public KodDocROVPD32Column createKodDocROVPD32Column() {
        return new KodDocROVPD32Column();
    }

    /**
     * Create an instance of {@link YearNColumn }
     * 
     */
    public YearNColumn createYearNColumn() {
        return new YearNColumn();
    }

    /**
     * Create an instance of {@link CodPilgColumn }
     * 
     */
    public CodPilgColumn createCodPilgColumn() {
        return new CodPilgColumn();
    }

    /**
     * Create an instance of {@link IntColumn }
     * 
     */
    public IntColumn createIntColumn() {
        return new IntColumn();
    }

    /**
     * Create an instance of {@link IndTaxNumColumn }
     * 
     */
    public IndTaxNumColumn createIndTaxNumColumn() {
        return new IndTaxNumColumn();
    }

    /**
     * Create an instance of {@link Kod0Column }
     * 
     */
    public Kod0Column createKod0Column() {
        return new Kod0Column();
    }

    /**
     * Create an instance of {@link DGKodAssignment6Column }
     * 
     */
    public DGKodAssignment6Column createDGKodAssignment6Column() {
        return new DGKodAssignment6Column();
    }

    /**
     * Create an instance of {@link DGI4NomColumn }
     * 
     */
    public DGI4NomColumn createDGI4NomColumn() {
        return new DGI4NomColumn();
    }

    /**
     * Create an instance of {@link EDRPOUColumn }
     * 
     */
    public EDRPOUColumn createEDRPOUColumn() {
        return new EDRPOUColumn();
    }

    /**
     * Create an instance of {@link Decimal12ColumnR }
     * 
     */
    public Decimal12ColumnR createDecimal12ColumnR() {
        return new Decimal12ColumnR();
    }

    /**
     * Create an instance of {@link DGKodСausesOperation6Column }
     * 
     */
    public DGKodCausesOperation6Column createDGKodCausesOperation6Column() {
        return new DGKodCausesOperation6Column();
    }

    /**
     * Create an instance of {@link MadeYearColumn }
     * 
     */
    public MadeYearColumn createMadeYearColumn() {
        return new MadeYearColumn();
    }

    /**
     * Create an instance of {@link StrColumn }
     * 
     */
    public StrColumn createStrColumn() {
        return new StrColumn();
    }

    /**
     * Create an instance of {@link KodOpColumn }
     * 
     */
    public KodOpColumn createKodOpColumn() {
        return new KodOpColumn();
    }

    /**
     * Create an instance of {@link DGI4LzColumn }
     * 
     */
    public DGI4LzColumn createDGI4LzColumn() {
        return new DGI4LzColumn();
    }

    /**
     * Create an instance of {@link Decimal2Column }
     * 
     */
    public Decimal2Column createDecimal2Column() {
        return new Decimal2Column();
    }

    /**
     * Create an instance of {@link EcoCodePollutionColumn }
     * 
     */
    public EcoCodePollutionColumn createEcoCodePollutionColumn() {
        return new EcoCodePollutionColumn();
    }

    /**
     * Create an instance of {@link DGKodTypeDoc61Column }
     * 
     */
    public DGKodTypeDoc61Column createDGKodTypeDoc61Column() {
        return new DGKodTypeDoc61Column();
    }

    /**
     * Create an instance of {@link Decimal0Column }
     * 
     */
    public Decimal0Column createDecimal0Column() {
        return new Decimal0Column();
    }

    /**
     * Create an instance of {@link DGI3NomColumn }
     * 
     */
    public DGI3NomColumn createDGI3NomColumn() {
        return new DGI3NomColumn();
    }

    /**
     * Create an instance of {@link KodDocROVPD31Column }
     * 
     */
    public KodDocROVPD31Column createKodDocROVPD31Column() {
        return new KodDocROVPD31Column();
    }

    /**
     * Create an instance of {@link DGSignColumn }
     * 
     */
    public DGSignColumn createDGSignColumn() {
        return new DGSignColumn();
    }

    /**
     * Create an instance of {@link DGNPNColumn }
     * 
     */
    public DGNPNColumn createDGNPNColumn() {
        return new DGNPNColumn();
    }

    /**
     * Create an instance of {@link DHead.LINKEDDOCS.DOC }
     * 
     */
    public DHead.LINKEDDOCS.DOC createDHeadLINKEDDOCSDOC() {
        return new DHead.LINKEDDOCS.DOC();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeclarContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DECLAR")
    public JAXBElement<DeclarContent> createDECLAR(DeclarContent value) {
        return new JAXBElement<DeclarContent>(_DECLAR_QNAME, DeclarContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DHead.LINKEDDOCS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LINKED_DOCS", scope = DHead.class)
    public JAXBElement<DHead.LINKEDDOCS> createDHeadLINKEDDOCS(DHead.LINKEDDOCS value) {
        return new JAXBElement<DHead.LINKEDDOCS>(_DHeadLINKEDDOCS_QNAME, DHead.LINKEDDOCS.class, DHead.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SOFTWARE", scope = DHead.class)
    public JAXBElement<String> createDHeadSOFTWARE(String value) {
        return new JAXBElement<String>(_DHeadSOFTWARE_QNAME, String.class, DHead.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HPASSISS", scope = DBody.class)
    public JAXBElement<String> createDBodyHPASSISS(String value) {
        return new JAXBElement<String>(_DBodyHPASSISS_QNAME, String.class, DBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HSHOT", scope = DBody.class)
    public JAXBElement<String> createDBodyHSHOT(String value) {
        return new JAXBElement<String>(_DBodyHSHOT_QNAME, String.class, DBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HREG", scope = DBody.class)
    public JAXBElement<String> createDBodyHREG(String value) {
        return new JAXBElement<String>(_DBodyHREG_QNAME, String.class, DBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HFNAME", scope = DBody.class)
    public JAXBElement<String> createDBodyHFNAME(String value) {
        return new JAXBElement<String>(_DBodyHFNAME_QNAME, String.class, DBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HPASSDATE", scope = DBody.class)
    public JAXBElement<String> createDBodyHPASSDATE(String value) {
        return new JAXBElement<String>(_DBodyHPASSDATE_QNAME, String.class, DBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HAPT", scope = DBody.class)
    public JAXBElement<String> createDBodyHAPT(String value) {
        return new JAXBElement<String>(_DBodyHAPT_QNAME, String.class, DBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HRAJ", scope = DBody.class)
    public JAXBElement<String> createDBodyHRAJ(String value) {
        return new JAXBElement<String>(_DBodyHRAJ_QNAME, String.class, DBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HPASS", scope = DBody.class)
    public JAXBElement<String> createDBodyHPASS(String value) {
        return new JAXBElement<String>(_DBodyHPASS_QNAME, String.class, DBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HCORP", scope = DBody.class)
    public JAXBElement<String> createDBodyHCORP(String value) {
        return new JAXBElement<String>(_DBodyHCORP_QNAME, String.class, DBody.class, value);
    }

}
