= iGov.ua APIs

== Overview
Портал державних послуг

=== Version information
Version: 1.0

=== Contact information
Contact: support@igov.ua

Terms of service: https://github.com/e-government-ua/i/wiki

=== URI scheme
Host: localhost
BasePath: /

=== Tags

* task-variable-collection-resource: Task Variable Collection Resource
* historic-process-instance-variable-data-resource: Historic Process Instance Variable Data Resource
* deployment-resource-resource: Deployment Resource Resource
* user-collection-resource: User Collection Resource
* task-identity-link-family-resource: Task Identity Link Family Resource
* historic-activity-instance-query-resource: Historic Activity Instance Query Resource
* process-instance-identity-link-collection-resource: Process Instance Identity Link Collection Resource
* simple-workflow-resource: Simple Workflow Resource
* group-resource: Group Resource
* ActionEventController -- События по действиям и статистика: Action Event Controller
* historic-task-instance-identity-link-collection-resource: Historic Task Instance Identity Link Collection Resource
* ECPCommonController -- наложение электронной подписи: ECP Common Controller
* execution-resource: Execution Resource
* historic-process-instance-query-resource: Historic Process Instance Query Resource
* process-instance-variable-collection-resource: Process Instance Variable Collection Resource
* model-collection-resource: Model Collection Resource
* form-data-resource: Form Data Resource
* process-definition-properties-resource: Process Definition Properties Resource
* historic-task-instance-collection-resource: Historic Task Instance Collection Resource
* AccessCentralController -- Доступ центральный: Access Central Controller
* task-event-collection-resource: Task Event Collection Resource
* ActionIdentityCommonController: Action Identity Common Controller
* historic-variable-instance-query-resource: Historic Variable Instance Query Resource
* group-membership-collection-resource: Group Membership Collection Resource
* с — Действия эскалаций: Action Escalation Controller
* FinanceCentralController -- Финансовые и смежные сущности: Finance Central Controller
* group-membership-resource: Group Membership Resource
* process-definition-resource-data-resource: Process Definition Resource Data Resource
* SubjectController - субъекты  и смежные сущности: Subject Controller
* process-definition-resource: Process Definition Resource
* process-definition-identity-link-collection-resource: Process Definition Identity Link Collection Resource
* process-definition-identity-link-resource: Process Definition Identity Link Resource
* ActionFeedBackController — Действия фидбэков: Action Feed Back Controller
* historic-process-instance-resource: Historic Process Instance Resource
* ProcessSubjectController — Иерархия процессов: Process Subject Controller
* task-event-resource: Task Event Resource
* execution-variable-data-resource: Execution Variable Data Resource
* historic-activity-instance-collection-resource: Historic Activity Instance Collection Resource
* SubjectCommonController — Организационная иерархия: Subject Common Controller
* properties-collection-resource: Properties Collection Resource
* task-sub-task-collection-resource: Task Sub Task Collection Resource
* task-attachment-collection-resource: Task Attachment Collection Resource
* task-variable-resource: Task Variable Resource
* ObjectPlaceController -- Обьекты мест (населенных пунктов и регионов) и стран: Object Place Common Controller
* task-identity-link-resource: Task Identity Link Resource
* DebugCentralController -- Дебаг и тест центральный: Debug Central Controller
* task-query-resource: Task Query Resource
* task-collection-resource: Task Collection Resource
* job-collection-resource: Job Collection Resource
* ObjectController -- Обьекты и смежные сущности: Object Controller
* model-resource: Model Resource
* user-info-resource: User Info Resource
* task-attachment-resource: Task Attachment Resource
* signal-resource: Signal Resource
* task-resource: Task Resource
* historic-task-instance-query-resource: Historic Task Instance Query Resource
* historic-process-instance-identity-link-collection-resource: Historic Process Instance Identity Link Collection Resource
* task-comment-resource: Task Comment Resource
* SubjectMessageCommonController -- Сообщения субьектов: Subject Message Common Controller
* task-identity-link-collection-resource: Task Identity Link Collection Resource
* FinanceCommonController -- Финансы общие (в т.ч. платежи): Finance Common Controller
* task-comment-collection-resource: Task Comment Collection Resource
* job-resource: Job Resource
* historic-detail-data-resource: Historic Detail Data Resource
* historic-variable-instance-collection-resource: Historic Variable Instance Collection Resource
* process-definition-model-resource: Process Definition Model Resource
* ActionHistoryController -- История по документам: Action History Controller
* MUController -- контроллер для взаимодействия с веб сервисом министерства юстиции: MU Controller
* process-definition-collection-resource: Process Definition Collection Resource
* ActionItemController - Предметы действий (каталог сервисов): Action Item Controller
* process-definition-image-resource: Process Definition Image Resource
* table-collection-resource: Table Collection Resource
* table-data-resource: Table Data Resource
* user-resource: User Resource
* historic-process-instance-collection-resource: Historic Process Instance Collection Resource
* process-instance-variable-data-resource: Process Instance Variable Data Resource
* process-instance-collection-resource: Process Instance Collection Resource
* historic-process-instance-comment-resource: Historic Process Instance Comment Resource
* historic-task-instance-resource: Historic Task Instance Resource
* process-instance-diagram-resource: Process Instance Diagram Resource
* SubjectMessageController -- Сообщения субьектов: Subject Message Controller
* execution-collection-resource: Execution Collection Resource
* DocumentAccessController -- Доступы к документам: Document Access Controller
* historic-detail-query-resource: Historic Detail Query Resource
* process-instance-variable-resource: Process Instance Variable Resource
* task-variable-data-resource: Task Variable Data Resource
* AccessCommonController — Доступ общий (права доступа к сервисам): Access Common Controller
* deployment-collection-resource: Deployment Collection Resource
* ActionTaskCommonController — Действия общие задач: Action Task Common Controller
* DocumentController -- Документы и смежные сущности: Document Controller
* deployment-resource: Deployment Resource
* ObjectFileCommonController -- Обьекты файлов общие: Object File Common Controller
* execution-query-resource: Execution Query Resource
* deployment-resource-data-resource: Deployment Resource Data Resource
* RelationController — Обработка Relation: Relation Controller
* ExportCommonController -- вызов стороннего АПИ: Export Common Controller
* process-instance-resource: Process Instance Resource
* ActionExecuteController: Action Execute Controller
* execution-variable-resource: Execution Variable Resource
* historic-process-instance-comment-collection-resource: Historic Process Instance Comment Collection Resource
* deployment-resource-collection-resource: Deployment Resource Collection Resource
* historic-detail-collection-resource: Historic Detail Collection Resource
* historic-variable-instance-data-resource: Historic Variable Instance Data Resource
* model-source-resource: Model Source Resource
* ActionFlowController — Действия очередей (слоты потока, расписания и тикеты): Action Flow Controller
* execution-variable-collection-resource: Execution Variable Collection Resource
* historic-task-instance-variable-data-resource: Historic Task Instance Variable Data Resource
* table-columns-resource: Table Columns Resource
* DocumentCommonController -- Проверки наложености ЭЦП по строкам-подписантам: Document Common Controller
* table-resource: Table Resource
* job-exception-stacktrace-resource: Job Exception Stacktrace Resource
* process-instance-identity-link-resource: Process Instance Identity Link Resource
* group-collection-resource: Group Collection Resource
* SubjectGroupController — Организационная иерархия: Subject Group Controller
* model-source-extra-resource: Model Source Extra Resource
* ActionTaskCentralController -- Действия задачи центрально: Action Task Central Controller
* user-info-collection-resource: User Info Collection Resource
* user-picture-resource: User Picture Resource
* process-instance-query-resource: Process Instance Query Resource
* task-attachment-content-resource: Task Attachment Content Resource
* DebugCommonController - Дебаг и тест общий: Debug Common Controller
* process-engine-resource: Process Engine Resource
* execution-active-activities-collection-resource: Execution Active Activities Collection Resource


