= iGov.ua APIs

== Overview
Портал державних послуг

=== Version information
Version: 1.0

=== Contact information
Contact: support@igov.ua

Terms of service: https://github.com/e-government-ua/i/wiki

=== URI scheme
Host: localhost
BasePath: /

=== Tags

* SubjectMessageCommonController -- Сообщения субьектов: Subject Message Common Controller
* с — Действия эскалаций: Action Escalation Controller
* FinanceCommonController -- Финансы общие (в т.ч. платежи): Finance Common Controller
* FinanceCentralController -- Финансовые и смежные сущности: Finance Central Controller
* SubjectController - субъекты  и смежные сущности: Subject Controller
* ActionExecuteController: Action Execute Controller
* ActionFeedBackController — Действия фидбэков: Action Feed Back Controller
* ActionItemController - Предметы действий (каталог сервисов): Action Item Controller
* ProcessSubjectController — Иерархия процессов: Process Subject Controller
* ActionFlowController — Действия очередей (слоты потока, расписания и тикеты): Action Flow Controller
* ActionEventController -- События по действиям и статистика: Action Event Controller
* SubjectGroupController — Организационная иерархия: Subject Group Controller
* DebugCentralController -- Дебаг и тест центральный: Debug Central Controller
* SubjectMessageController -- Сообщения субьектов: Subject Message Controller
* AccessCentralController -- Доступ центральный: Access Central Controller
* ActionTaskCentralController -- Действия задачи центрально: Action Task Central Controller
* DocumentAccessController -- Доступы к документам: Document Access Controller
* ObjectController -- Обьекты и смежные сущности: Object Controller
* AccessCommonController — Доступ общий (права доступа к сервисам): Access Common Controller
* ActionIdentityCommonController: Action Identity Common Controller
* ActionTaskCommonController — Действия общие задач: Action Task Common Controller
* DocumentController -- Документы и смежные сущности: Document Controller
* DebugCommonController - Дебаг и тест общий: Debug Common Controller
* ObjectPlaceController -- Обьекты мест (населенных пунктов и регионов) и стран: Object Place Controller
* ObjectFileCommonController -- Обьекты файлов общие: Object File Common Controller


