
== Стандарты создания контроллера с сервисами в нем
:hardbreaks:

[source,java]
----
@Controller
@Api(tags = { "ActivitiRestTestController" }, description = "Охрана стены черным дозором")
@RequestMapping(value = "/test")
public class ActivitiRestTestController {
   private static final Logger LOG = LoggerFactory.getLogger(ActivitiRestTestController .class); 
    @Autowired
    private TestEntityDao testEntityDao;    
 
    // 1
    @ApiOperation(value = "Поход за стену", notes = "Подробное описание сервиса: поход за стену" )
    @ApiResponses(value = { @ApiResponse(code = 304, message = "Катастрофа, белые ходоки победили"),
      @ApiResponse(code = 500, message = "Ошибка, белые ходоки не найдены")} )
    @RequestMapping(value = "/doSomething", method = RequestMethod.GET)
    public @ResponseBody void doSomething(){
        LOG.info("do smth");
        testEntityDao.doSomething();
    }   
 
    // 2
    @ApiOperation(value = "Добавление дозорного", notes = "Подробное описание сервиса: добавление дозорного" )
    @RequestMapping(value = "/setEntity", method = RequestMethod.GET)
    public @ResponseBody Entity setEntity(
            @ApiParam(value = "id дозорного", required = false) @RequestParam(value = "nID", required = false) Long nID ,
            @ApiParam(value = "имя дозорного", required = true) @RequestParam(value = "sName") String sName)
            throws CommonServiceException {
        try {
            return testEntityDao.saveOrUpdate(nID, sName);
        } catch (Exception e){
            throw new CommonServiceException("ex in controller!", e);
        }
    }

    // 3
    @ApiOperation(value = "Вызов дозорного", notes = "Подробное описание сервиса: вызов дозорного" )
    @RequestMapping(value = "/getEntity", method = RequestMethod.GET)
    public ResponseEntity<Entity> getEntity(
            @RequestParam(value = "nID") Long nID) throws CommonServiceException {
        Entity entity = testEntityDao.getById(nID);
        if (entity == null) {
            throw new CommonServiceException(
                    ExceptionCommonController.BUSINESS_ERROR_CODE,
                    "Record not found. No such Entity with nID=" + nID,
                    HttpStatus.FORBIDDEN);
        }
        return new ResponseEntity<>(entity, HttpStatus.OK);
    }
}
----

.Комментарии:
- контроллер называем по названию корневой сущности, начиная с ActivitiRest, например ActivitiRestSubjectController ля сущности Subject, ActivitiRestCountryController -- для Country и т.п.
- Если видите, что сервисы можно "дописать" в существующий контроллер -- дописывайте (например, в контроллере ActivitiRestDocumentController есть сервисы для работы с Document, DocumentType и DocumentContentType)
- более точное форматирование можно посмотреть здесь: #723, т.е. по "результатам" этой задачи
- по возможности, делаем метод-"сеттер" <2>, который либо добавляет новую запись, либо обновляет ее, и начинается со слова set (примеры можно посмотреть в вышеперечисленных контроллерах)
- вариант, когда сущность "заворачивается" в ResponseEntity <3>, используется в случаях, когда сервисы будут вызываться в Активити (сохраняется кодировка). Но таких случаев пока немного. Во всех остальных случаях достаточно просто возвращать эту сущность <2>.
- исключения. Желательно бросать CommonServiceException, которое "отлавливается" и преобразовывается в джейсоновский обьект с ошибкой вида: {code: "code", message: "message"} Также оно сразу логируется (уровень error) -- т.е. такие исключения можно отдельно не логировать. Есть разные конструкторы, вплоть до выбора http-статуса ошибки и "передачи" исходного исключения (методы <2> и <3>, плюс можно посмотреть в самом классе CommonServiceException)


**__Пояснения по применению Swagger-аннотаций:__**

```java
@Api(tags = { "ActivitiRestTestController" }, description = "Охрана стены черным дозором")
```
[NOTE]
====
.Это аннотация контроллера. Парамерты аннотации:
- **tags** - тег для обозначения контроллера. В документации он будет главой, а подглавами будут описания сервисов этого контроллера.
- **description** - кратакое описание контроллера
====


```java
@ApiOperation(value = "Поход за стену", notes = "Подробное описание сервиса: поход за стену" )
```
[NOTE]
====
.Это аннотация сервиса. Парамерты аннотации:
- **value** - назначение сервиса. Для описания назначения использовать существительные (Добавление а не Добавить ).
- **notes** - подробное описание сервиса с примерами. Для улучшения внешнего вида описания возможно применение языка разметки **MARKDOWN**, <<notesmarkdown, подробное описание>>
====


```java
@ApiResponses(value = { 
    @ApiResponse(code = 304, message = "Катастрофа, белые ходоки победили"),
    @ApiResponse(code = 500, message = "Ошибка, белые ходоки не найдены") })
```
[NOTE]
====
.Это Response аннотация сервиса. Параметры аннотации:
- **code** - HTTP код  возврата
- **message** - "Краткое описание HTML кода возврата"
 
Применяется, только если необходимо добавить или изменить описание кода возврата, повторять код по умолчанию нет необходимости. 

**Код возврата 200** имеет смысл описывать только если он возвращает неоднозначный результат. 

Например сервис **/login** возвращает неоднозначный результат: или **true** или **false**, в зависимости от правильности пароля. 

А вот при удалении записи результат однозначен: запись или удалена, или нет.

.Коды возврата по умолчанию.
- 200 OK
- 401 Unauthorized
- 403 Forbidden
- 404 Not Found
====


```java
@ApiParam(value = "id дозорного", required = false)
```
[NOTE]
====
.Это аннотация описания параматра запроса. Парамерты аннотации:
- **value** - краткое описание параметра
- **required** - в описании показывает обязательность или нет параметра, по-этому дополнительно описывать его в в подробном описании не нужно.

Описания параметров настоятельно рекомендуется делать при помощи этой аннотации. 

Если описание короткое, то достаточно описания только в этой аннотации.

Если описание слишком длинное, то здесь делается короткое, а полное описание заносится в поле notes аннотации **@ApiOperation**
====

