[[notesmarkdown]]
## Форматирование описания с помощью MARKDOWN
:hardbreaks:


**Так выглядит строка с описанием сервиса в контроллере:**
[source,java]
----
private static final String noteStartProcessByKey = "##### Заголовок описание процесса #####\n\n"
  + "HTTP Context: https://server:port/wf/service/action/task/start-process/{key}\n\n\n"
  + "HTTP Context: https://server:port/wf/service/action/task/start-process/{key}[я ссылка]\n\n\n"
  + "- **key** - Ключ процесса, выделен жирным\n"
  + "- **nID_Subject** - ID авторизированого субъекта, выделен жирным\n\n\n"
  + "Request:\n\n"
  + "https://test.region.igov.org.ua/wf/service/action/task/start-process/citizensRequest\n\n"
  + "Response:\n"
  + "\n```json\n";
  + "  {\n"
  + "    \"id\":\"31\"\n"
  + "  }\n"
  + "\n```\n";

  @ApiOperation(value = "Заголовок описание процесса", notes = noteStartProcessByKey)
----

**Так выглядит строка с описанием сервиса в документации:**
====
#####  Заголовок описание процесса (будет отдельной подглавой) #####


HTTP Context: https://server:port/wf/service/action/task/start-process/{key}

HTTP Context: https://server:port/wf/service/action/task/start-process/{key}[я ссылка]

- **key** - Ключ процесса, выделен жирным
- **nID_Subject** - ID авторизированого субъекта, выделен жирным

Request:

https://test.region.igov.org.ua/wf/service/action/task/start-process/citizensRequest

Response:

```json

  {
    "id":"31"
  }

```
====

**Важные замечания**

- Сигнатура начала блока кода обязательно должна быть в отдельной строке:
----
"\n```json\n";
----

- Сигнатура конца блока обязательно должна быть в отдельной строке:
----
"\n```\n";
----

- Кажной сигнатуре начала кода должна соответствовать сигнатура его окончания
----
"\n```json\n";
  ...здесь код...
"\n```\n";
----

- После конца списка обязательно должна быть пустая строка, иначе дальнейший текст будет считаться частью последнего пункта.
----
"- пункт 1\n"
"- пункт 2\n"
"- пункт 3\n\n"
----

Подробнее: http://asciidoctor.org/docs

