= iGov.ua APIs

== Overview
Портал державних послуг

=== Version information
Version: 1.0

=== Contact information
Contact: support@igov.ua

Terms of service: https://github.com/e-government-ua/i/wiki

=== URI scheme
Host: localhost
BasePath: /

=== Tags

* DocumentCommonController -- Проверки наложености ЭЦП по строкам-подписантам: Document Common Controller
* SubjectMessageCommonController -- Сообщения субьектов: Subject Message Common Controller
* с — Действия эскалаций: Action Escalation Controller
* FinanceCommonController -- Финансы общие (в т.ч. платежи): Finance Common Controller
* ObjectPlaceController -- Обьекты мест (населенных пунктов и регионов) и стран: Object Place Common Controller
* RelationController — Обработка Relation: Relation Controller
* ExportCommonController -- вызов стороннего АПИ: Export Common Controller
* SubjectGroupController — Организационная иерархия: Subject Group Controller
* ActionExecuteController: Action Execute Controller
* ActionHistoryController -- История по документам: Action History Controller
* ActionFeedBackController — Действия фидбэков: Action Feed Back Controller
* AccessCommonController — Доступ общий (права доступа к сервисам): Access Common Controller
* ActionIdentityCommonController: Action Identity Common Controller
* ActionTaskCommonController — Действия общие задач: Action Task Common Controller
* ProcessSubjectController — Иерархия процессов: Process Subject Controller
* ActionFlowController — Действия очередей (слоты потока, расписания и тикеты): Action Flow Controller
* DebugCommonController - Дебаг и тест общий: Debug Common Controller
* ObjectFileCommonController -- Обьекты файлов общие: Object File Common Controller
* ECPCommonController -- наложение электронной подписи: ECP Common Controller
* SubjectCommonController — Организационная иерархия: Subject Common Controller


